server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10000/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # Fair Service GET
        - id: fair-get
          uri: lb://FAIR-AND-NEWS-SERVICE
          predicates:
            - Path=/board/fairs/**
            - Method=GET
          filters:
            - RewritePath=/board/fairs/(?<segment>.*), /fairs/$\{segment}

        # Fair Service POST, PUT, DELETE
        - id: fair-modify
          uri: lb://FAIR-AND-NEWS-SERVICE
          predicates:
            - Path=/board/fairs/**
            - Method=POST, PUT, DELETE
          filters:
            - RewritePath=/board/fairs/(?<segment>.*), /fairs/$\{segment}

        # Reply Service GET(회원 별 작성한 댓글 조회)
        - id: reply-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/reply/member/**
            - Method=GET

        # Reply Service GET(게시물 별 댓글 조회)
        - id: reply-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/reply/board/replies/**
            - Method=GET

        # Reply Service GET(댓글 검색)
        - id: reply-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/reply/board/search/**
            - Method=GET

        # Reply Service POST(댓글 등록)
        - id: reply-post
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/reply/regist
            - Method=POST

        # Reply Service PUT(댓글 수정)
        - id: reply-put
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/reply/modify/**
            - Method=PUT

        # Reply Service DELETE(댓글 삭제)
        - id: reply-delete
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/reply/delete/**
            - Method=DELETE

        # Reply Service GET TEST
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
            
        # Member Service Feign Client 설정
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member-service/**
            - Method=POST, PUT, DELETE
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        # BOARD Service GET(회원이 작성한 게시글 조회)
        - id: post-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/posts/member/**
            - Method=GET

        # BOARD Service GET(회원이 좋아요한 게시글 조회)
        - id: post-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/posts/member/like/**
            - Method=GET

        # BOARD Service GET(일별 좋아요 5개이상 게시글 조회)
        - id: post-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/posts/day/like
            - Method=GET

        # BOARD Service GET(월별 좋아요 10개이상 게시글 조회)
        - id: post-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/posts/month/like
            - Method=GET

        # BOARD Service GET(선택한 게시글의 내용 조회)
        - id: post-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/posts/content/**
            - Method=GET

        # BOARD Service GET(선택한 게시글의 내용 조회)
        - id: post-get
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/posts/lists/**
            - Method=GET

        # BOARD Service POST(게시글 등록)
        - id: reply-post
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/post/new
            - Method=POST

        # BOARD Service PUT(게시글 수정)
        - id: reply-put
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/post/modify/**
            - Method=PUT

        # BOARD Service DELETE(게시글 삭제)
        - id: reply-delete
          uri: lb://POSTREPLY-SERVER
          predicates:
            - Path=/post/delete/**
            - Method=DELETE